#!/bin/sh
#
# nfs        Skip NFS startup
#

umask 077

start() {
	mkdir /root/sd
	if [ -e /dev/mmcblk0p2 ]; then mount /dev/mmcblk0p2 /root/sd ; fi
	if [ -e /dev/piton_sd2 ]; then mount /dev/piton_sd2 /root/sd ; fi
}

stop() {
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
